version: '3.2'

volumes:
  mongodb:

services:
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      - ENV MONGO_INITDB_ROOT_USERNAME=root
      - ENV MONGO_INITDB_ROOT_PASSWORD=v3fYS4cChLsX2pUYd8A6F62H

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=3eabURK4gqmtZRwzDKTxzBVV
      - RABBITMQ_DEFAULT_VHOST=rabbitmq

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DEV_DB_HOST=mongo
      - DEV_DB_USER=root
      - DEV_DB_PASSWORD=v3fYS4cChLsX2pUYd8A6F62H
      - DEV_QUEU_HOST=rabbitmq
      - DEV_QUEUE_USER=user
      - DEV_QUEUE_PASSWORD=3eabURK4gqmtZRwzDKTxzBVV
      - DEV_USE_AUTHENTICATION=false
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - 4040:4040

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 8080:4200
